### ISSUE TITLE
When using this action example crashes with invalid url

### ISSUE THREAD

**Issue by EndermanAPM** [misaelnieto/web_to_pdf_action#1]
The action spits out the following error:
##[error]Protocol error (Page.navigate): Cannot navigate to invalid URL

Config 
```
      - name: html to pdf
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPage: https://www.noenieto.com/resume/
          outputFile: ./path/to/my/resume.pdf
          pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
```
